name: Angular CI
on:
  push:
    branches:
      - '*'
jobs:
  install-and-test:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.16.x]
    steps:
      - uses: actions/checkout@master
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install and Test
        run: |
          bun install
          bun run lint
        env:
          CI: true
